// Auto-generated by scripts/texel_tuner.py
// Do not edit by hand. Values are from Texel logistic regression.

#ifndef WEIGHTS_EVALUATED_H
#define WEIGHTS_EVALUATED_H
#pragma once

constexpr int TUNED_PST_MG[7][64] = {
    {0},
    {   0,    0,    0,    0,    0,    0,    0,    0,
        8,   35,  -22,   -9,   10,   17,   -2,   18,
        3,   20,   22,   45,   46,  -23,   36,  -12,
       17,   14,   18,  -18,   14,  -11,   27,   26,
       12,   52,   42,    3,   31,   16,   -8,  -14,
        2,   21,    3,    0,   10,   11,   12,    5,
        5,    1,    2,    3,    2,    1,    9,    1,
        0,    0,    0,    0,    0,    0,    0,    0},
    {  -4,  -12,    3,   -1,   -6,    2,   17,   -3,
        2,   -1,   33,   11,   18,   11,  -15,   -4,
        4,    2,  -10,   -3,    8,   23,    6,    7,
       14,    1,  -20,   -9,   -4,    9,   -1,   -1,
        2,    1,    0,  -17,    1,    3,  -11,    2,
        0,    2,    7,    4,    6,   -2,    5,    0,
        7,    0,    8,   -4,   -2,    1,    0,    1,
        0,    0,    0,    2,    0,   -5,    1,    0},
    {  -4,    0,   33,   -1,   16,  -25,    0,    0,
        0,  -12,   -5,  -21,    5,    2,   21,    0,
       -2,    1,    6,   -6,    4,    3,    1,    5,
        0,   -5,   -1,    2,   -1,    3,   -1,    0,
       -7,   -5,    5,    3,    6,    1,  -15,   12,
      -13,    1,    5,   -2,    3,   -2,   12,   -7,
        1,   -2,  -10,   -3,  -12,   -2,   -1,    2,
       -6,  -14,   -1,    0,   -1,   -1,    2,  -22},
    {   2,   -5,   -1,   20,   12,    9,  -12,    1,
      -27,   -8,    5,   -6,   -2,   -1,    0,  -19,
        6,    0,    0,   -3,    0,    0,    0,   -9,
      -15,   -1,   -2,    1,   -2,  -12,    1,  -46,
      -13,   -3,   -4,   -4,    1,   -1,   -3,   -1,
       -9,   -1,    0,    2,   -1,   -4,   -1,   -7,
      -12,  -14,    3,    0,    1,    1,   -3,  -10,
        3,    2,   -1,   -2,    0,   -4,    4,    7},
    { -16,  -13,  -14,  -58,  -46,   -7,    3,  -16,
        0,   -1,  -47,  -18,   -5,   -3,   -1,   -6,
       -2,  -26,   -3,   -2,    0,   -2,    0,    2,
      -13,  -11,   -2,  -11,    0,   -2,  -24,  -14,
        0,   -5,   -7,   -4,   -3,  -12,   -2,  -34,
       -8,   -1,  -18,   -8,  -14,   -5,  -10,   -8,
       -3,   -6,   -2,  -31,  -11,   -3,   -9,  -13,
       -6,   -7,  -18,   -2,    1,   -7,  -13,  -11},
    {  -1,    3,   -5,   10,    8,    7,  -28,    7,
        2,   -2,   21,    7,   40,    6,    6,   -5,
        0,    5,   22,   11,  -19,  -20,   -9,  -17,
        0,    1,   -8,   -7,  -10,   -6,  -10,   -4,
        0,    0,   -2,    3,   -1,    0,    3,   -1,
        0,   -1,    1,    2,    1,    4,    0,    0,
        0,    0,    1,    0,    0,    1,    1,    0,
        0,   -2,   -2,   -1,    0,    0,   -2,   -1}
};

constexpr int TUNED_PST_EG[7][64] = {
    {0},
    {   0,    0,    0,    0,    0,    0,    0,    0,
       30,   23,   -7,  -18,  -12,    7,   15,   19,
        0,   13,   51,   16,   42,    6,   23,   15,
       33,   42,   47,   23,   75,   27,    9,   -4,
       20,   21,   16,   30,   26,   39,   37,    2,
       15,   14,   25,    4,   19,   19,   21,   12,
       18,    1,   17,   17,    5,   11,   17,   10,
        0,    0,    0,    0,    0,    0,    0,    0},
    {  -2,   10,    7,   -4,  -13,   -3,    2,   -2,
        0,    0,   21,   10,   20,   12,   -3,   -1,
        6,    3,   -3,   -1,   19,    4,    4,   14,
        5,   -3,   -3,    3,   18,    9,   -2,    0,
        2,    1,    2,   -4,   24,    3,   -8,    1,
        0,    5,    9,    8,   11,   -1,   20,    0,
        2,    0,   16,   -4,    0,    6,    0,    2,
        1,    1,    1,    2,    1,   -3,    1,    0},
    {  -2,   -1,   -8,   -1,   12,    1,    1,   -3,
        1,    4,   -6,  -17,    2,    3,    5,    0,
       -7,    2,   13,    6,    4,   10,   -2,   11,
       -1,    0,   16,    8,    0,   -1,   -3,   -3,
       -8,   -1,   23,   21,   41,   11,   -3,    2,
       -3,    2,   15,    6,    7,    1,   11,    3,
        1,    1,   -5,   -5,   -6,   -3,    1,    4,
       -4,   -8,   -2,    0,    0,   -4,    6,  -12},
    { -10,    4,    4,   23,    6,   11,  -14,   25,
      -15,   -5,    8,   -5,   -2,    3,    9,  -25,
       10,    2,   -2,   -3,   -1,    1,    0,   -6,
       -9,   -3,   -1,    4,    0,  -10,   -3,  -31,
       -8,   -2,   -1,    3,    8,   -1,   -2,    3,
       -6,   -2,    2,   -2,   -2,   -3,   -3,    4,
      -17,   -3,    3,    4,   -5,    7,    5,  -14,
        4,    2,   -2,   -2,    0,   -1,    3,    2},
    { -20,  -14,  -17,  -42,  -51,   -8,    2,  -17,
        0,    0,  -34,   -8,   -6,   -4,   -1,   -4,
       -3,  -11,   -5,   -4,    0,   -2,    0,    3,
      -23,   -7,   -2,  -11,    2,   -5,  -17,  -11,
        4,   -2,  -10,   -6,   -1,  -13,   -5,  -25,
      -11,   -1,  -16,   -7,  -12,   -7,   -8,   -8,
        3,   -5,   -1,  -24,  -10,   -5,   -6,  -11,
       -3,   -7,  -15,   -1,    2,   -4,  -10,   -8},
    {  -4,    5,  -19,  -22,    6,    1,  -34,   12,
        4,    2,    9,  -24,    4,   15,  -22,  -22,
       -3,    0,   16,   29,    5,  -11,   18,  -17,
        0,    4,   -7,    1,   11,   14,   -5,  -14,
        1,    1,    5,   11,    8,   21,   24,   -9,
       -9,   -2,    8,   11,    8,   29,   -3,   -1,
       -5,   -4,    4,    3,   -2,    2,    2,    0,
       -1,   -6,   -7,  -15,   -2,   -5,  -21,   -8}
};

constexpr int TUNED_BISHOP_PAIR = -31;
constexpr int TUNED_TEMPO = 50;
constexpr int TUNED_KING_PROX = 3;
constexpr int TUNED_EVAL_BIAS = 50;

// ---------------------------------------------------------------------------
// Extra tunables (defaults match eval.cpp)
// ---------------------------------------------------------------------------

constexpr int TUNED_MG_PIECE_VALUE[7] = {0, 100, 330, 500, 550, 1500, 0};
constexpr int TUNED_EG_PIECE_VALUE[7] = {0, 100, 300, 330, 500, 950, 0};

constexpr int TUNED_CENTER_MG_WEIGHT[7] = {0, 6, -2, -3, -3, -5, 0};
constexpr int TUNED_CENTER_EG_WEIGHT[7] = {0, 2, 2, 3, 3, 4, 6};

constexpr int TUNED_KING_PROX_DIST_BASE = 10;

constexpr int TUNED_TRADE_RISK_SCALE_PCT = 70;

constexpr int TUNED_MK_BONUS_MAX = 100;
constexpr int TUNED_MK_TARGET = 8;
constexpr int TUNED_MK_MISSING_SQUARE_WEIGHT = 12;
constexpr int TUNED_MK_IN_CHECK_SCALE_PCT = 50;

constexpr int TUNED_CONSTRAINT_BASE = 220;
constexpr int TUNED_CONSTRAINT_CAP = 70;
constexpr int TUNED_CONSTRAINT_TRIGGER_MK_MAX = 1;
constexpr int TUNED_RICHNESS_BASE_MAX = 120;
constexpr int TUNED_RICHNESS_MIN = 20;
constexpr int TUNED_RICHNESS_PIECES_CAP = 30;
constexpr int TUNED_RICHNESS_PIECE_PENALTY = 3;

constexpr int TUNED_TRADE_ATTACKER_NEG_SEE_DIV = 5;
constexpr int TUNED_TRADE_QUEEN_PAWN_PENALTY = 20;
constexpr int TUNED_TRADE_SMALL_VICTIM_DIV = 2;
constexpr int TUNED_TRADE_ATTACKER_SMALL_VICTIM_DIV = 6;

constexpr int TUNED_MOBILITY_RISKY_CAP_WEIGHT = 3;
constexpr int TUNED_MOBILITY_SAFE_CAP_WEIGHT = 8;

constexpr int TUNED_KING_ATTACK_OPP_NONKING_MAX = 1;
constexpr int TUNED_KING_ATTACK_ACTIVITY_DIST_BASE = 10;
constexpr int TUNED_KING_ATTACK_ACTIVITY_WEIGHT = 8;
constexpr int TUNED_KING_ATTACK_ATTACKER_PULL_DIST_BASE = 14;
constexpr int TUNED_KING_ATTACK_ATTACKER_PULL_WEIGHT = 2;
constexpr int TUNED_KING_ATTACK_BOOSTED_MK_DIV = 2;

constexpr int TUNED_KING_AGGRESSION_MAT_DIFF_THRESHOLD = 400;
constexpr int TUNED_KING_AGGRESSION_PHASE_MARGIN = 2;
constexpr int TUNED_KING_AGGRESSION_DIST_BASE = 12;
constexpr int TUNED_KING_AGGRESSION_WEIGHT = 6;

constexpr int TUNED_PAWN_ADVANCE_RANK_WEIGHT = 2;

constexpr int TUNED_FIFTY_MOVE_THRESHOLD = 60;
constexpr int TUNED_FIFTY_MOVE_PENALTY_PER_PLY = 3;

#endif // WEIGHTS_EVALUATED_H
